travis:
  secure:
    BINSTAR_TOKEN: rFcROk6B3zPMNJofenE+QeJrC70xyhsURCy0rFCBIOL8NoPc0jvxeHNJrTk8WPTJvFi3ov4IeA+pc9JPqvfrpTvNtBpdIb1HmQ4u9upxT9qgytkfJUDS5gV/0BD33gHlGCrZnP3S2YnXMfDJkfWOgj3uC6kms6p+co8xwdcsHKUp6NjOdc66+epes/WNGfsdEtG76oQEjFKSvtWq3NPhd2/hYzHVzDedI9zr7mDesN19nvFi8JhX8VLSNAPFJJ8i1yqzuEnrNq8K/jHG1rn9OH2p5tvFfMZltWQqxEh62gogI8Uq2zimVC9IPFzFkhBPIofpho6vU1rii/iCwlfJNuix54x1aN4B3eEFid6SeBduf5Eds843WaQTaQfAaRO3CBKjncFxSxb/0T/PPWp9iIpOvWWU1rThf/qOjHsT8Sc9Yd7Qpmw3pbUQ5F5S6xOPCu1k5QJKgK0Swo343SNR0BY480LopN7FKjuIxFmiO6HxvjFh1EWVAT82ObnLIec+n93VqzqIKUODt2UH8VIpbHrJ+2hFnkObT6jkjl5+IaQZi5DbT3wIvgH6oVL15BnyxOUR9oQ+xX/D5MW3L/cG2YyoAS4OUzz1JNr8G1O8qa2fP8wMOyNA1zdtgnA8W2NyUgdLDkEkHTjm1oSi/6KaWCsxkTQrc6DeJzDuSD58+uU=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
